void print_indentation(int depth);
void print_ast(struct program* head);
void print_program(struct program* head, int depth);
void print_f_def(struct function_definition* f_dec, int depth);
void print_f_dec(struct function_declaration* f_dec, int depth);
void print_dec(struct declaration* f_dec, int depth);
void print_typespec(typespec_type type, int depth);
void print_id(char* id, int depth);
void print_param_list(struct parameter_list* p_list, int depth);
void print_param_dec(struct parameter_declaration* p_dec, int depth);
void print_f_body( struct function_body* f_body, int depth);
void print_statement(struct statement* stt, int depth);
void print_declaration(struct declaration* dec, int depth);